# basic configuration
font pango: Roboto 12
set $mod Mod4
set $alt Mod1
set $shift Shift
workspace_layout default
new_window pixel 1
floating_modifier $mod

# colors
set_from_resource $bg i3wm.color0 #f0f0f0
set_from_resource $fg i3wm.color7 #f0f0f0

# variables
set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $ws4 "4"
set $ws5 "5:notes"
set $ws6 "6"
set $ws7 "7:vm"
set $ws8 "8"
set $ws9 "9"
set $ws10 "10"
set $ws11 "11:www"

# workspace outputs
workspace $ws1 output HDMI-0
workspace $ws2 output HDMI-0
workspace $ws3 output DP-0
workspace $ws4 output DP-0
workspace $ws5 output HDMI-0
workspace $ws6 output DP-0
workspace $ws7 output HDMI-0
workspace $ws8 output DP-0
workspace $ws10 output HDMI-0
workspace $ws11 output HDMI-0

# theme and appearance
# client.focused          $fg     $bg     $fg     $fg     $fg
# client.focused_inactive $bg     $bg     $fg     $bg     $bg
# client.unfocused        $bg     $bg     $fg     $bg     $bg
# client.urgent           $bg     $bg     $fg     $bg     $bg
# client.placeholder      $bg     $bg     $fg     $bg     $bg
# client.background       $bg

# bar {
#   output HDMI-0
#   status_command i3status
# }
