# startup applications (once)
exec --no-startup-id /usr/bin/lxpolkit
exec --no-startup-id ~/.config/i3/scripts/monitors
exec --no-startup-id wal -s -i ~/Pictures/wallpapers/current
exec --no-startup-id copyq --start-server
exec --no-startup-id /usr/bin/dunst --config ~/.config/dunst/dunstrc
exec --no-startup-id sleep 2 && /usr/bin/brave
exec --no-startup-id i3-msg "workspace 4; layout tabbed"

# startup applications (always)
exec_always --no-startup-id autotiling
exec_always --no-startup-id sleep 1 && ~/.config/i3/scripts/start-polybar
exec_always --no-startup-id sleep 2 && picom --config ~/.config/picom/picom.conf
exec --no-startup-id sleep 3 && ~/.config/i3/scripts/idle-manager
