#!/usr/bin/env bash
set -euo pipefail

volume_step=1
max_volume=100

# Uses regex to get volume from pactl
function get_volume {
  pactl get-sink-volume @DEFAULT_SINK@ | grep -Po '[0-9]{1,3}(?=%)' | head -1
}

# Main function - Takes user input, "up", "down", or "mute", and performs the corresponding action
case "${1:-}" in
up)
  # Unmutes and increases volume, then displays the notification
  pactl set-sink-mute @DEFAULT_SINK@ 0
  volume=$(get_volume)
  if [ $(("$volume" + "$volume_step")) -gt $max_volume ]; then
    pactl set-sink-volume @DEFAULT_SINK@ $max_volume%
  else
    pactl set-sink-volume @DEFAULT_SINK@ +$volume_step%
  fi
  ;;

down)
  pactl set-sink-volume @DEFAULT_SINK@ -$volume_step%
  ;;

mute)
  pactl set-sink-mute @DEFAULT_SINK@ toggle
  ;;
esac
