#!/bin/bash
repo=$(checkupdates 2>/dev/null | wc -l)
aur=$(yay -Qua 2>/dev/null | wc -l)
total=$((repo + aur))

if [[ $total -gt 0 ]]; then
  notify-send -u normal "Updates Available" "$repo repo, $aur AUR"
else
  notify-send -u low "System up-to-date" "No updates available"
fi

