hl.config({ autogenerated = false })

require("conf.env")
require("conf.monitors")
require("conf.input")
require("conf.appearance")
require("conf.keybinds")
require("conf.windowrules")
require("conf.autostart")

-- XWAYLAND
-- XWayland can't scale itself; windows render pixelated on scaled outputs.
-- force_zero_scaling keeps them unscaled. No-op at scale=1 but cheap
-- insurance for future HiDPI. Per wiki.
hl.config({
	xwayland = {
		force_zero_scaling = true,
	},
})

-- PERMISSIONS
-- Precautionary OBS/portal fix: enforcement defaults off without
-- ecosystem.enforce_permissions. Real fix was installing
-- xdg-desktop-portal-hyprland.
hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
