font pango:Roboto 12
set $mod Mod4
set $alt Mod1
set $shift Shift
workspace_layout default
default_border pixel 1
floating_modifier $mod normal

set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $ws4 "4"
set $ws5 "5:notes"
set $ws6 "6"
set $ws7 "7:vm"
set $ws8 "8"
set $ws9 "9"
set $ws10 "10"
set $ws11 "11:www"

workspace $ws1 output HDMI-A-1
workspace $ws2 output HDMI-A-1
workspace $ws3 output DP-1
workspace $ws4 output DP-1
workspace $ws5 output HDMI-A-1
workspace $ws6 output DP-1
workspace $ws7 output HDMI-A-1
workspace $ws8 output DP-1
workspace $ws10 output HDMI-A-1
workspace $ws11 output HDMI-A-1

# class                  border    bg        text      indicator child_border
client.focused          #62a0ea   #101928   #deddda   #62a0ea   #62a0ea
client.focused_inactive #282828   #101928   #9a9996   #282828   #282828
client.unfocused        #282828   #101928   #9a9996   #282828   #282828
client.urgent           #ed333b   #101928   #deddda   #ed333b   #ed333b
client.placeholder      #282828   #101928   #9a9996   #282828   #282828
client.background       #101928
