exec dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=sway

exec /usr/bin/lxpolkit
exec copyq --start-server
exec /usr/bin/dunst --config ~/.config/dunst/dunstrc
exec sleep 2 && /usr/bin/brave
exec sleep 3 && ~/.config/sway/scripts/idle-manager

exec_always wal -b swaybg -s -i ~/Pictures/wallpapers/current
exec autotiling
exec_always sleep 1 && ~/.config/sway/scripts/start-waybar
