#!/bin/bash

SOUND_LOW="/usr/share/sounds/freedesktop/stereo/message-new-instant.oga"
SOUND_NORMAL="/usr/share/sounds/freedesktop/stereo/message.oga"
SOUND_CRITICAL="/usr/share/sounds/freedesktop/stereo/dialog-warning.oga"

play_sound() {
  [ -f "$1" ] && paplay "$1" 2>/dev/null
}

# dunst passes: appname summary body icon urgency
URGENCY="${@: -1}"

if [ "$1" == "VolumeControl" ]; then
  exit 0
fi

case "$URGENCY" in
CRITICAL)
  play_sound "$SOUND_CRITICAL"
  ;;
LOW)
  play_sound "$SOUND_LOW"
  ;;
*)
  play_sound "$SOUND_NORMAL"
  ;;
esac
