include theme.conf

font_size 13
# adjust_line_height 0
enable_audio_bell no

font_family      JetBrainsMono Nerd Font

map ctrl+space no_op
map ctrl+shift+t nop
map ctrl+shift+n nop
map ctrl+shift+left nop
map ctrl+shift+right nop
map ctrl+shift+up nop
map ctrl+shift+down nop

cursor_shape block
cursor_shape_unfocused unchanged
cursor_underline_thickness 2.0
cursor_blink_interval -1
cursor_stop_blinking_after 0
shell_integration no-cursor

window_padding_width 1 3

confirm_os_window_close 0
